version: 2
jobs:
  build:
    working_directory: ~/express-typescript-react-redux-universal
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:4.8.2
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run: 
          name: Where am I
          command: 'pwd; ls'
      - run:
          name: Install npm 
          command: 'cd api; sudo npm install'
      - run: 
          name: Where am I
          command: 'pwd; ls'
      - run:
          name: tests
          command: 'cd api; npm run test'
