version: 2
eneral:
  branches:
    only:
      - master
      - develop
jobs:
  build:
    working_directory: ~/express-typescript-react-redux-universal/api
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm
          command: sudo npm install
      - run:
          name: tests
          command: npm run test
 